### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by jrowen**
This addresses #40 by implementing the build approach suggested by @ungil.  When merged, you may want to update the package README to note the package is also functional on Windows.

### CODE REVIEW

**Comment by armstrtw** [comment]
Can you revert this bit:
rblpapi.Rproj → Rblpapi.Rproj

all else looks good.

Thanks,
Whit

**Comment by jrowen** [comment]
Sorry about that.  Let me know if you find anything else.

**Comment by armstrtw** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
:+1: 

Still traveling so it'll be a moment til I can look more closely but this is very good news. Thanks to all who helped make this happen.

**Pull request merged**
