### PR TITLE
check if user define remote resources

### PR DESCRIPTION
**Pull request by creamy-gurkin**
Hi,
I'm not sure if this is the correct branch to merge to, but I wanted to use the library on a machine not directly connected to the internet and didn't see a variable to update for that use case so I added one. I'm also unsure about where to update the documentation on this variable, but if you let me know then I wouldn't mind updating that as well as well as update anything else you think I might have missed.

Many thanks.

### CODE REVIEW

**Comment by johnlaing** [comment]
Could you share a bit more about your use case? The package does require a connection to Bloomberg to be usable, so I'm wondering if you might be heading down a dead end by installing on a machine with no internet.

**Comment by creamy-gurkin** [comment]
@johnlaing my use case is being behind a corporate firewall and although we do have a connection to Bloomberg, there are various reasons for me not to want to open a connection to github. This way we can load the resources locally and build the package with little issue. I see this as a small and isolated adjustment to the library and a fine feature for anyone in my position. :-)

@eddelbuettel no problem. I assume you'll want to maintain control of the naming of the variables in the main configure so I just chose some generic names for the snippet but since it isn't a function with return you'll have to call it once per download block. Just let me know if anything else needs changing. Also I used the -z test since I figured knowing whether or not val was an empty string might be useful.

**Comment by eddelbuettel** [comment]
@creamy-gurkin I think you misunderstood 100%.  I didn't ask you to add `/tmp/snippet.sh`.  I showed you in that file what changes I was expecting you to make to `configure`.    

It would also be nice you could log the change to `configure` in the file `ChangeLog` with a name and email address.

**Comment by eddelbuettel** [comment]
I am going to close this and replace it with quick and simple new PR.   "Works here" as they say and will give it some more testing paces.

In this example I set both `blpLibrary` and `blpHeaders` to local files, the `configure` echos in two lines starting with `** using ...` that it deploys them.  If unset, downloads will be made as usual.

```sh
edd@rob:~/git/rblpapi(feature/local_archive_option)$ blpLibrary=/tmp/demo/blpLibrary.tar.gz blpHeaders=/tmp/demo/blpHeaders.tar.gz R CMD INSTALL .
* installing to library ‘/usr/local/lib/R/site-library’                                                                                                                                                            
* installing *source* package ‘Rblpapi’ ...
** using non-staged installation via StagedInstall field                                                                                                                                                           
Setting up compilation for a linux 64-bit system
** using /tmp/demo/blpHeaders.tar.gz
** using /tmp/demo/blpLibrary.tar.gz
** libs
[.... rest of compilation omitted ... ]
```

**Comment by eddelbuettel** [comment]
Replaced by #362

**Comment by creamy-gurkin** [comment]
Sure, sorry I was less responsive. My thanks for the update.

**Pull request closed without merging**
