### PR TITLE
add support for portfolio data (closes #169)

### LINKED ISSUE #169: bds returns null when requesting portfolio data
bds function returns null when you request portfolio data.

The call bds("U13140014-39 Client","PORTFOLIO_DATA") returns portfolio details in excel but returns NULL in R.

### PR DESCRIPTION
**Pull request by johnlaing**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Looks great. Only minor question (or suggestion): should it be `getPortfolio()` for consistence as it is a getter?  Or not because bds, bdp, bdh, ... are shorthand?

**Comment by johnlaing** [comment]
I don't have a preference either way. Happy to change if you'd like.

**Comment by eddelbuettel** [comment]
As a user (and author) I do prefer `getFoo()` for various foo, so if you're up for a search+replace I think it makes it easier.  But as I said, here we do have counter examples -- and if the Bloomberg documentation refers to 'portfolio' as a function ...   So your call.

**Comment by johnlaing** [comment]
I'll change it. I like bdp/bds/bdh for their simplicity, but there are others like `getTicks`. I suppose this is more similar to the latter.

**Pull request merged**
