### PR TITLE
Add getTicks2 to support condition codes

### PR DESCRIPTION
**Pull request by joel23888**
Addresses #117. Aiming to supersede this and eventually retire getTicks2 with #147.

### CODE REVIEW

**Comment by ClarkHenry** [comment]
Any idea when this will be pushed to production? Thanks.

**Comment by joel23888** [comment]
@ClarkHenry I have not had time (yet) to return to #147. I have started using another tick source with condition codes, which means I am uncertain on when I will look at this. Would you like to help?

**Comment by ClarkHenry** [comment]
Sorry, I must have misunderstood. I thought this pull request was intended to add a new function called getTicks2. So, shall this pull request be removed (i.e., I should not anticipate a new version with getTicks2)?

**Comment by eddelbuettel** [comment]
The previous attempt always returned an xts.  An xts required data to fit a matrix which excludes condition codes (unless we map them to ints).

I have been meaning to extend several functions to also return a data.table object.

**Comment by eddelbuettel** [comment]
I plan to revert this commit.  We were never fans of the commit as it needlessly duplicates a function.

The obvious narrow fix is to just a return the condition code in the `data.frame` object, and exclude that column in the `xts` and `fts` objects.

The better solution is also return a `data.table`.  Those are very powerful and efficient and allow sorting by  different indices such as symbol or date.  I can't work on that now but may get to it during the week.

**Comment by armstrtw** [comment]
so, regarding data.frame does he publish a c api for it?  that we will 'LinkTo' or is it just a data.frame w/ some added attributes?

**Comment by eddelbuettel** [comment]
Can you try again?   Who is "he"?  What is "it"?  I do not understand your post.

`getTicks2()` is a pretty poor carbon copy of `getTicks()` returning one more column.  We can do better in `getTicks()` and I plan to, also offering `data.table` return.   I haven't gotten to it as I worked on the very exciting [anytime](https://github.com/eddelbuettel/anytime) package the last few days.

**Comment by eddelbuettel** [comment]
If you were asking about `data.table` then 'No' there is no C API (though I requested one) so the conversion would happen at the R level -- as we currently do anyway when we switch between `data.frame`, `xts`, `fts` and what not.

**Comment by armstrtw** [comment]
I was referring to the data.table maintainer, Matt Dowle, and thanks for the follow up answer.

Just let me know if you need any help on this.  I don't use these functions much, so I've generally left them alone.

**Comment by eddelbuettel** [comment]
Gotcha.  These days `data.table` is mostly referred to as "by Matt and Arun".

**Comment by eddelbuettel** [comment]
And how to do do returns of time series-natured data affects more than one function.   But let's deal with one a  time.

Does your `fts` allow non-numeric data?

**Comment by armstrtw** [comment]
no, it's based on an R array/matrix.  but the backend is a template class, so changeable with some work.

**Comment by eddelbuettel** [comment]
Yes and no. The trouble is that `data.frame` does not lend itself to templating on one (C++) class.

**Comment by joel23888** [comment]
I am also happy to help. If I am following you correctly:
* `getTicks_Impl` will return condition codes in the `data.frame`
* `getTicks` will still return data.frame by default, but we will offer a return type of `data.table` as well, and strip off condition codes for return types that do not support them

Is this consistent with what you were intending?

**Comment by eddelbuettel** [comment]
Pretty much, yes.  Was hoping I might get to it this evening.

**Comment by joel23888** [comment]
Would it be a good idea to add columns of type `IDate` and `ITime` in the case a `data.table` is returned? Perhaps this is specific to me, but I often find that with ticks or bars I want to analyze based on time-of-day rather than a specific point in time. If it is common enough, it might be good to add these.

**Comment by eddelbuettel** [comment]
Yes, that is the `data.table` way of things I have been trying to get used to.  Will do.

**Comment by eddelbuettel** [comment]
I have some initial support in a new branch `feature/getTicks-revamped` -- maybe you and other could test this? 

Basic idea is that `data.table` return type gets us just that:

```bash
~/git/rblpapi(feature/getTicks-revamped)$ r -lRblpapi -p -e'getTicks("ES1 Index", returnAs="data.table")[1:10]'
          date     time  type   value size
 1: 2016-09-16 19:33:27 TRADE 2142.00    1
 2: 2016-09-16 19:33:49 TRADE 2141.75    1
 3: 2016-09-16 19:34:11 TRADE 2142.00    1
 4: 2016-09-16 19:34:39 TRADE 2141.75    1
 5: 2016-09-16 19:34:56 TRADE 2142.00    1
 6: 2016-09-16 19:35:25 TRADE 2142.25    1
 7: 2016-09-16 19:35:25 TRADE 2142.25    1
 8: 2016-09-16 19:37:05 TRADE 2142.00    1
 9: 2016-09-16 19:37:56 TRADE 2142.25    1
10: 2016-09-16 19:38:50 TRADE 2142.25    1
~/git/rblpapi(feature/getTicks-revamped)$ 
```

There is some still-commented out code in the C++ function about `conditionCodes` which will need another look ...

**Comment by eddelbuettel** [comment]
Needed to sleep over it to realize that I of course needed to re-enable support for _condition codes_ which is now a little smarter than it used to be.  It all works just fine now:

```bash
~/git/rblpapi(feature/getTicks-revamped)$ r -lRblpapi -p -e'getTicks("ES1 Index", returnAs="data.table")[]'                                                                                
            date     time  type   value size conditionCode
   1: 2016-09-16 05:38:19 TRADE 2136.50    2          TSUM
   2: 2016-09-16 05:38:19 TRADE 2136.50    2            AS
   3: 2016-09-16 05:38:19 TRADE 2136.50    1            OR
   4: 2016-09-16 05:38:19 TRADE 2136.50    1            OR
   5: 2016-09-16 05:38:19 TRADE 2136.50    1          TSUM
  ---                                                     
2107: 2016-09-16 06:37:58 TRADE 2137.50    1            AS
2108: 2016-09-16 06:37:58 TRADE 2137.50    1            OR
2109: 2016-09-16 06:38:06 TRADE 2137.25    1          TSUM
2110: 2016-09-16 06:38:06 TRADE 2137.25    1            AS
2111: 2016-09-16 06:38:06 TRADE 2137.25    1            OR
~/git/rblpapi(feature/getTicks-revamped)$ 
```

Pull request should come later today.

**Comment by eddelbuettel** [comment]
So it is in now as PR #200 which @armstrtw already accepted.   One very minor question:  should we keep it as column name `conditionCode` or get it more on line as something shorter and all-lowercase?  Maybe `condcode` ? Or how about `condition`?

**Comment by joel23888** [comment]
I would say something like `condcode` would work well. Sorry but I did not have a chance to test this due to some network issues.

**Comment by eddelbuettel** [comment]
As they say in politics, "that is something I can get behind" so I just made that switch.  `condcode` it is.

**Comment by hakki13** [comment]
Is there plan to add other fields (as condcode) to be returned when asking tick information? Equities have interesting information such as Show Exchange Code - Show BIC/MIC code. Is it possible to somehow get these with condition code?

**Comment by eddelbuettel** [comment]
I would think so.  With the switch to `data.table` as a format, we can support non-numeric fields easily. 

Can you cook up a pull request?

**Comment by hakki13** [comment]
I have never opened one, nor do I have expertise fix this issue. Will open one, if there it is mandatory that I can help to fix it.

**Comment by eddelbuettel** [comment]
Let's slow down a little; I think what you just did may not have been what you wanted.

**Comment by hakki13** [comment]
I agree, is there away to just reverse all my actions?

**Comment by eddelbuettel** [comment]
No need to.  The master branch is unaffected.

**Comment by hakki13** [comment]
Quick question and I know this might not be right place, but... I forked Rblpapi package and created a clone. Copied get_ticks function in a new file and made (what I think) needed changes. Was able to stage, commit and push them to my forked github repository. I thought that I could install that forked package via devtools and test out if my code actually works, but I can't get to install. Other packages installs with no problem. Is that way to test changes or is there better way to do this?

**Comment by eddelbuettel** [comment]
If and when you made local changes, you should be able to just install locally:
- `R CMD INSTALL .`  on the command line from the directory
- 'build and reload'' (or whatever it is called) in RStudio
- ... any other method from source (`devtools::build()` ?)

You _do_ have the local sources, you do _not_ need devtools to go remote.

**Comment by hakki13** [comment]
yeah, that fails as well, so I'm not a package builder just yet. Thanks for responding. Will keep working on it.

**Comment by eddelbuettel** [comment]
Helps to try to make sure you locally build the unmodified CRAN or upstream package.  Devils is always in the details...

**Comment by hakki13** [comment]
You have a point there, that didn't work either so must be missing something. Thanks for help.

**Pull request merged**
