### PR TITLE
fix download.file call for OSX build

### PR DESCRIPTION
**Pull request by martinbel**
added method='libcurl' in the download.file as it wasn't working.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thank you!  You may be our first OS X user!

**Comment by martinbel** [comment]
No problem, it was easy to fix the error. I actually wasn't able to connect after installing the package. Any suggestions?

```
> library(Rblpapi)
> con <- blpConnect() 

08DEC2015_02:21:26.305 71785:4342456320 ERROR blpapi_platformtransporttcp.cpp:671 blpapi.session.transporttcp.{1}.<localhost:8194> Connection failed 

08DEC2015_02:21:26.305 71785:4342456320 WARN blpapi_platformcontroller.cpp:371 blpapi.session.platformcontroller.{1} Platform: 0 failed 1 consecutive connect attempts, stopped trying to reconnect. 
```

**Comment by eddelbuettel** [comment]
I presume you did set a user, password and host as `options()`. Even then, connection sometimes fails. To monitor this I fetch hourly data via `getBars()` once an hour. This often fails in the evening; I sometimes also have an error on fresh session.  

If your id is valid with Bloomberg this should work.

**Comment by wmorgan85** [comment]
You won't be able to use Bloomberg via OS X unless you are using Server
API. Desktop API requires local installation of the Bloomberg software and
this is only on Windows. See http://www.bloomberglabs.com/api/libraries/ for
details.

**Comment by eddelbuettel** [comment]
Some of us had luck with Windows in a VM ...

**Comment by wmorgan85** [comment]
Yes, that's the best way when on OS X. I personally use Parallels but it's
up to your personal preference.

**Pull request merged**
