### PR TITLE
Fix BDS segfault 

### PR DESCRIPTION
**Pull request by klin333**
Fix BDS crashes from #253

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks for reworking this.  We work by an informal "majority of guilty parties onboard" rule so I will wait for either @johnlaing or @armstrtw to pipe in but this is otherwise fine by me.

**Comment by armstrtw** [comment]
I like the new patch. It's minimally invasive.

Please do keep the test code in your own branch.  It will be useful to resurrect if any additional bugs surface later on.

**Review by eddelbuettel — APPROVED** [review]
Nice work -- approved!

**Comment by eddelbuettel** [comment]
@armstrtw Can you maybe hit the approve button for the code review? I just did the same, but it would be good if we had two (or more) "formal" hand shakes on this.

**Review by armstrtw — APPROVED** [review]

**Pull request merged**
