### PR TITLE
add sanity checks for bbgDateToJulianDate

### PR DESCRIPTION
**Pull request by armstrtw**
given how poor bbg data integrity is, I think we need these checks in place.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Sure. Checks are good.

One Q for you though:  do we actually really want Julian dates or was that just a way to get dates as ints?  Rcpp has (still poor, to be rewritten) Rcpp::Date around R's date, and we do of course have Boost Date_Time.

**Comment by armstrtw** [comment]
not sure I'm following you.

**Comment by eddelbuettel** [comment]
Why have Julian date when we can have a native Date type?

Why translate into a scheme nobody uses (Julian) when we can have one humans and computers can use as easily?

**Comment by armstrtw** [comment]
but Julian is just R's date type, right (days since 1970-01-01)?  what am I missing?

**Comment by eddelbuettel** [comment]
We are getting closer!  

See [Wikipedia for Julian Date](https://en.wikipedia.org/wiki/Julian_date) or just `help(julian)` (and scroll to the end!!) to clear up some of your confusion.

```r
R> today <- Sys.Date()
R> today
[1] "2016-03-02"
R> julian(today, -2440588)      # actual Julian day as defined
[1] 2457450
attr(,"origin")
[1] -2440588
R> as.integer(today)        # my preferred form, and what R's Date type uses internally
[1] 16862
R> 
```

Maybe you always uses the `julian()` function with the epoch as an offset --- _highly nonstandard_.

So I think we agree on what we should do -- store today, say, as 16862.  We refer to it in two different ways, and yours may risk being misunderstood as it was by me :)

**Comment by armstrtw** [comment]
Ahh, yes.  I think we agree.  and funny that I found this:
http://whatis.techtarget.com/definition/Julian-date
2) Commonly in computer programming, Julian date has been corrupted to mean the number of elapsed days since the beginning of a particular year. For example, in this usage, the Julian date for the calendar date of 1998-02-28 would be day 59.

So, what I mean is that we should return the data as R's 'Date' class, or days since 1970-01-01.

If you look at the conversion function, all should be clear, and please let me know if you think we should return as a different type.
https://github.com/Rblp/Rblpapi/blob/feature-add-checks-for-julian-date-conversion/src/blpapi_utils.cpp#L70

and the new one for converting doubles:
https://github.com/Rblp/Rblpapi/blob/feature-add-checks-for-julian-date-conversion/src/blpapi_utils.cpp#L80

This patch doesn't change the return format from master.  I just added checks to make sure BBG didn't give us a date with 'time' parts, which we would then ignore by converting to an R date.

**Comment by eddelbuettel** [comment]
If you already returned 16862 then it is just a matter of renaming away the misleading Julian label :)

**Comment by armstrtw** [comment]
ok, you want me to rename the functions as part of this patch?

**Comment by armstrtw** [comment]
Is there a name for R's date format, other than just RDate or something similar?

**Comment by eddelbuettel** [comment]
In R, `Date`

In Rcpp, `Rcpp::Date` (pretty much a one-to-one map; just try it).

In R'c C API:  I think INTSXP with class attribute, need to check.

**Comment by armstrtw** [comment]
Yes.  for now we're using C API  INTSXP.

Ok. for now I'm just renaming things.  If we want to change the tooling, that's more of a major change and I would prefer to do it as a separate patch.

**Comment by eddelbuettel** [comment]
Please don't.

My medium-term goal is to get rid of all SEXP use.  This is a C++ project.  Why not use the niceties such as ctor, dtor, exceptions, ... ?

`Rcpp::Date` is ready for you.  RQuantLib has used it for a decade, also interchanging with Boost.

Happy to do cleanup but let's not add more SEXP line noise.

**Comment by armstrtw** [comment]
this is a patch to add error checking.  switching tooling is outside the scope of this patch.

I'm happy to switch to more Rcpp as I have been doing in all the recent code I've added, and I can do as a separate patch, which I've already said.

**Comment by eddelbuettel** [comment]
Indeed. Working code trumps good-but-empty intentions.  Onto the TODO list...

**Comment by armstrtw** [comment]
updated to rename those functions.

Let's have a separate discussion about how you want to change this particular code to make use of Rcpp.

**Pull request merged**
