### PR TITLE
release 0.3.9 (closes #290)

### LINKED ISSUE #290: Staged installs
I received mail from BDR about an upcoming R 3.6.0 change which will be activated by March 1:

> This concerns packages

> EmiStatR ProjectTemplate RVowpalWabbit Rblpapi bayesdfa bigMap bmlm
distrEllipse franc gWidgets2 ganalytics glmmfields nimble polidata prcbench
race rfishbase spdynmod trialr uavRst walker zonator

> Staged installation is to be a new feature of R 3.6.0: it is not yet the
default in R-devel but it is scheduled to become so on Mar 1.  To turn it on
before then, set environment variable R_INSTALL_STAGED=true : this has been
done for the fedora-clang results on CRAN.

> Tomas Kalibera has written a blog about this which can be seen at
https://developer.r-project.org/Blog/public/2019/02/14/staged-install/index.html
.  For most of these packages he has some analysis of the issues at
https://github.com/kalibera/rstagedinst/tree/master/hardcoded
and is happy to help with interpretation (he is Cc:ed here).

> Please adjust your package to work with staged installation, if possible
before Mar 1.  A stopgap measure is to opt out by adding

> StagedInstall: no

> in the DESCRIPTION file, and the CRAN team will do that for any remaining
packages on which others depend (currently EmiStatR ProjectTemplate Rblpapi
gWidgets2 nimble rfishbase) when the default is switched.

I am inclined to do a minimal maintenance releases taking the existing package and just adding that one suggested line as I cannot currently test Rblpapi.

Thoughts?

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by johnlaing** [comment]
I'm a bit confused here. This commit is a direct child of at 0.3.8, and skips over everything else that was done in the last year.

Perhaps we are thinking differently about what constitutes a minimal maintenance release. If this commit is intended to constitute a standalone release (which I would be ok with), then I think it should not be merged into master.

**Comment by eddelbuettel** [comment]
Here is my reasoning:

1)  It is a standalone release. See the branch -- it is 
     - a one-line change to DESCRIPTION as discussed and requested by CRAN
     - an update to a now-dead URL in NEWS (harmless)
     - minor edits to NEWS as we had fscked up making the last release 0.3.7 AND 0.3.8 (harmless)
     - a one line addition to .Rbuildignore
     - NOTHING ELSE
2) That got rolled up into 0.3.9 and sits at CRAN.  As minimal as we can make it, and we both agreed on that.
3)  Also committed in a new branch I split off right at 0.3.8

All good so far?

Now, I fear the branch will one day get deleted and lost as a stale branch.  So I figure given that we _actually also need all the changes enumerated above in master itself_ we may as well merge.

But I am open. If you'd rather redo all those (minimal) changes by hand a second time in master you can.  The changes have to go in, so we may as well preserve the commit and work record, no?

But as I said, open to other suggestions..

**Comment by johnlaing** [comment]
Fair enough

**Comment by eddelbuettel** [comment]
CRAN found a few more stale bloomberglabs URLs (in README.md and the vignette) so I scanned more carefully and updated all (ie in configure too).

**Comment by eddelbuettel** [comment]
Ok, and just wiggled the changes away from a merge conflict.

I suggest we squash merge this once we have green light from CRAN. (If we don't squash merge we probably get a pretty ugly long branch from 0.3.8 to HEAD.)

**Comment by eddelbuettel** [comment]
And green light from Uwe so merging now.

**Comment by eddelbuettel** [comment]
Package *still* in waiting at CRAN and I am getting a little irritated. I sent daily follow-ups.

Anyway, now added to the [ghrr drat](http://ghrr.github.io/drat/) and announced on r-sig-finance with BCC to @alfredkanzler and @johnlaing .

**Comment by eddelbuettel** [comment]
Version 0.3.10 is now at CRAN.

http://dirk.eddelbuettel.com/cranberries/2019/04/07#Rblpapi_0.3.10

**Pull request merged**
