### PR TITLE
Feature/argument checking

### PR DESCRIPTION
**Pull request by eddelbuettel**
this had bitten a colleague ...

### CODE REVIEW

**Comment by johnlaing** [comment]
Just curious - why `call.=FALSE` ?

**Comment by eddelbuettel** [comment]
Stylistic.  I like it better.  How about you?

**Comment by eddelbuettel** [comment]
As in:

```r
R> johndemoWithout <- function() stop("Foo because of bar.")
R> johndemoWith <- function() stop("Foo because of bar.", call.=FALSE)
R> johndemoWithout()
Error in johndemoWithout() (from #1) : Foo because of bar.
R> johndemoWith()
Error: Foo because of bar.
R> 
```

**Comment by johnlaing** [comment]
I tend to prefer more descriptive messages. When different functions can break with the same error message, how else do you know where the problem is?
```r
> fwith <- function() stop("something broke")
> fwithout <- function() stop("something broke", call.=FALSE)
> g <- function() if (runif(1) > 0.5) fwith() else fwithout()
> g()
Error: something broke
> g()
Error in fwith() : something broke
```

**Comment by eddelbuettel** [comment]
a) Having the mindset of interactive work, so I just called the function, no need to repeat it back to.
b) In the programmatic / deeper nested case, I think `traceback()` still leads to the origin:

```r
R> traceback()
2: stop("Foo because of bar.", call. = FALSE) at #1
1: johndemoWith()
R> 
```

**Comment by eddelbuettel** [comment]
Given how we make everything optional, we could have that bool an option too.  [ I am kidding ;-) ]

**Comment by johnlaing** [comment]
I frequently work in non-interactive settings, I guess that's the difference.

**Comment by eddelbuettel** [comment]
I do too, littler and all that.  I just don't like the default look of `stop()`.

**Pull request merged**
