### PR TITLE
unique-ify timestamps before merge of multiple ticks (closes #76)

### LINKED ISSUE #76: getMultipleTicks(..., returnAs="xts") is broken
We rely on xts to merge the bid, ask, trade, ... vectors but the timestamps are not unique.  So the merged xts is not valid.

### PR DESCRIPTION
**Pull request by eddelbuettel**
Pending more testing against live data, thanks to @joshuaulrich for the follow-up yesterday.  

I'll follow up here if once I hear from the colleague you spotted the "infelicity" in the first place.

### CODE REVIEW

**Comment by johnlaing** [comment]
This looks straightforward enough, but I don't use `xts` so I have no independent view on whether this makes sense.

**Comment by eddelbuettel** [comment]
You did read that I write 'pending testing', right?   ;-)  
Should be all good though.  I did some casual testing last eve, but someone is going to over it with a finer comb to make sure that right bid/ask value precede trades etc.

**Comment by johnlaing** [comment]
I did, but I misunderstood what you meant. To me, a pull request means "this is ready to go". So I merged it...

**Comment by eddelbuettel** [comment]
How about if we agree that PRs are invitation for comment by other team members.  If I wanted to commit directly, I would (and do, for trivial things).

**Pull request merged**
