### PR TITLE
add additional intraday raw fields to getTicks and getMultipleTicks functions

### PR DESCRIPTION
**Pull request by hakki13**
I don't have much knowledge but found these fields from Bloomberg API PDF.

req.Set "includeExchangeCodes", "TRUE" 
req.Set "includeConditionCodes", "TRUE" 
req.Set "includeBrokerCodes", "TRUE" 
req.Set "includeRpsCodes", "TRUE" 
req.Set "includePlottableEvents", "TRUE"

From earlier pull request saw similar field, as functions already return ConditionCodes. I would request to set up optional raw data fields to be imported as well.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I am confused. This PR seems to wrap several unrelated commits.  Is that what you wanted?

(It's ok to be new at git.  We all were/are at some point.  Just ask.)

**Comment by hakki13** [comment]
No it wasn't. As said never opened one and not sure why other comments where included in it. My apologies

**Comment by eddelbuettel** [comment]
No harm, that is just a dead (non-merged) branch. 

If you can compile Rblpapi yourself, the easiest is to i) fork the repo, ii) pull down a version to your machine, iii) work out a change and iv) commit it and push it back to your repo at gh.  The pull request is then just the clean difference between what we have and what you have which can be nicely localized and minimal.

**Comment by hakki13** [comment]
ok, will try to work that out. Apologies again.

**Comment by eddelbuettel** [comment]
No worries.  We all had people to lean on for first steps.  Look around for some tutorials, the ones at github are good as are ones at related hosting companies.  And of course StackOverflow and all that.

**Pull request closed without merging**
