### PR TITLE
add check for results vector matching order of securities vector

### PR DESCRIPTION
**Pull request by armstrtw**
simple string compare to check that the order of the results vector matches what we expect.  the new code uses seqNumber from bbg to determine the row number in the results vector.  This check just insures that the seqNumber matches the proper position in the securities argument.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks for the PR merge, looks good.

And the usual plea of pretty please also adding ChangeLog or NEWS.Rd, or else I'll do it :)

**Comment by armstrtw** [comment]
do you have a way of producing the changelog from the git log? or do you just edit by hand?

**Comment by eddelbuettel** [comment]
If you use the One True Editor Everyone Should Use and hit 'C-x 4 a' then it inserts name, timestamp, file, routine, ... for you.  I do not know if vim, eclipse, atom, ... can be taught to be that clever.

And because it is so 'cheap' for me to do it I keep doing it...

**Comment by eddelbuettel** [comment]
I looked into a few git2changelog scripts but didn't like any.  In practice I have a few nice git aliases here and scribble it from those:

```
[color]
	ui = true
[alias]
	st = status
	ci = commit
	co = checkout
	ls = log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
        ll = log --pretty=format:\"%C(yellow)%h%Cred%d %Creset%s%Cblue [%cn]\" --decorate --numstat
        hist = log --graph --decorate --pretty=oneline --abbrev-commit
```

**Comment by armstrtw** [comment]
TH was recently telling us about Magit.  He really likes it, but I haven't tried it yet.  Not sure if it has something similar built in.

**Comment by eddelbuettel** [comment]
I followed up in Slack with a few recommendations...

**Comment by armstrtw** [comment]
one question.  how do you tell it your name? I was able to figure out email, but not the name it generates.

**Comment by eddelbuettel** [comment]
Hold on.  I think I set that in `~/.emacs` for some things (like the different changelog mode for Debian packages).

Found it in the `~/.emacs` at work:

```
;; make changelog entries complete
(setq user-mail-address "d......@k.........com")
(setq user-full-name "Dirk Eddelbuettel")
```

**Comment by armstrtw** [comment]
thanks!

**Comment by armstrtw** [comment]
you want me to make a PR for the changelog or that ok w/ you to just push?

**Comment by eddelbuettel** [comment]
I think if it is just ChangeLog you may as well push.  And no need for one ChangeLog entry per commit, but one (or more) per PR seems right.

**Pull request merged**
