### PR TITLE
Updated getBars - support for adjustmentFollowDPDF

### PR DESCRIPTION
**Pull request by joel23888**
This is a potential solution for adjusting intraday bar requests for corporate actions such as stock splits.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
@joel23888 I'd like to revisit this, but possibly as one option in a to-be-added new options or overrides vector.  I'd rather not expand the interface with a bunch of toggles at the top-level.  Thoughts?

**Comment by joel23888** [comment]
Thanks. I think a vector approach would be good because there are currently several options. It might also be worthwhile thinking about what defaults make sense. Would you want to default to adjusting for corporate actions or following DPDF?

Also, would you include gapFillInitialBar in the vector as well?

**Comment by eddelbuettel** [comment]
Yup.  I'm out and about right now so can't take a detailed look right now but a single (named) vector may do,  potentially also overrides.   

Might be best to list a few options and have test function or two.   So your help in this is greatly appreciated. ;-)

**Comment by joel23888** [comment]
Happy to help, but I will have to look at this in more detail next week. Initial thoughts:
* From the BBG API developer's guide the intraday bar request does not seem to have any overrides. So it would seem just a named vector for the options to be passed.
* It makes sense to include gapFillInitialBar in the vector. How do we avoid breaking code already using this option explicitly?
* For testing these, one relevant check to see if it is working is around corporate actions like stock splits. A recent example would be a 10 for 1 split in 8956 (Japanese stock), effective 10/28/15.

**Comment by eddelbuettel** [comment]
Quickly:
- nice, extracting _names_ (for keys) and _values_ is then trivial
- we can keep it as a final (named) argument, test for being present (ie `missing()` will be `FALSE`) and then warn; the positional use may well die; that is a pill we may have to swallow
- can you spec two quick call, with and without the option, to see how it affects the return data pre/post split?

**Comment by joel23888** [comment]
@eddelbuettel I am busy with other things at the moment but I will return to this when things free up.

**Comment by joel23888** [comment]
@eddelbuettel I can take a look at this - for the two calls you mentioned do you mean pick a corporate action and show expected behavior?

**Comment by eddelbuettel** [comment]
@joel23888 yes, I guess my idea was to show a call _without_ the option set and then one _with it set_ so that we see in changed output that it was actually affecting the outcome as planned.

**Comment by joel23888** [comment]
@eddelbuettel I have something working but no defaults. I think by default the behavior should reflect gapFillInitialBar=TRUE and adjustmentFollowDPDF=TRUE (after testing if it not passed then it will not adjust by default). What do you think and if you agree what is the preferred way to default?

**Comment by joel23888** [comment]
@eddelbuettel You can see some of the tests I ran on this at:
https://github.com/joel23888/Rblpapi/commit/22d46985e578e1c4fad48a6e21102381131276bc

Let me know on the defaults and I'll make any adjustments and submit a new pull request.

**Comment by eddelbuettel** [comment]
The tests look good.  (The commit is "dirty" as you included dll files...)  A new (or modified) pull request would be good, this moves in the right direction!

**Comment by eddelbuettel** [comment]
Can you make that a new or updated pull request? I can always clean up / adjust afterwards.

**Comment by joel23888** [comment]
Submitted a new one. Or let me know if you prefer me to clean up on Monday. Whatever works for you.

**Pull request closed without merging**
