### PR TITLE
Default blpAuthenticate object support

### PR DESCRIPTION
**Pull request by randomee**
- add support for a default blpAuthenticate() object
-  add support for that default blpid object to be used by functions that
    support identity argument
- documentation for these changes

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Looks like something didn't work as you planned:

```r
Error: package or namespace load failed for ‘Rblpapi’:
 .onAttach failed in attachNamespace() for 'Rblpapi', details:
  call: assign("blpAuth", blpAuth, envir = .pkgenv)
  error: object 'blpAuth' not found
Error: loading failed
Execution halted
ERROR: loading failed
```

**Comment by eddelbuettel** [comment]
From a look at `init.R` you mixed you assignment into the code for `con` which may not be a good idea -- but in any event failed to provide a fallback for `blpAuth` so that's why it goes belly up with the option is FALSE.

**Comment by eddelbuettel** [comment]
@randomee Please advise whether you plan to correct this currently broken PR or whether we should close it.

**Comment by eddelbuettel** [comment]
Ok, I dropped a quick commit in to at least have it _build_.  Someone who actually _uses_ authentication will have to assess if/how well this works.

**Comment by randomee** [comment]
Sorry, busy with the 1st day of the trading year.  Thank you for fixing my typo.  Copy/paste due to firewall, etc. mea culpa.

One thing in your patch.  You moved blpAutoAuthenticate outside of blpAutoConnect.  It doesn't make much sense to try to authenticate unless you're connected.  You need a valid connection object to send an authentication request.  I think it should be dependent on blpAutoConnect.  But I can see either way.

(Having it try to auth, will fail w/ a message about missing a connection.  Having it nested could "fail silently" leading to confusion.  Could also make blpAutoAuthenticate force blpAutoConnect = TRUE.)

Below is a log of it working.  Happy to test further cases if you have something else to test.

```
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> testIP <- "x.x.x.x"
> testUUID <- "xxxxxxxx"
> testSAPI <- "x.x.x.x"
> options("uuid" = testUUID)
> options("blpIP" = testIP)
> options("blpHost" = testSAPI)
> options("blpAutoConnect" = TRUE)
> options("blpAutoAuthenticate" = TRUE)
>
> library(Rblpapi)
Rblpapi version 0.3.8.1 using Blpapi headers 3.8.18.1 and run-time 3.8.18.1.
Please respect the Bloomberg licensing agreement and terms of service.
> bdp("IBM US Equity", "NAME")
                                     NAME
IBM US Equity INTL BUSINESS MACHINES CORP
>
```

**Comment by randomee** [comment]
And testing against a desktop API 
```
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> testDesktop<-"x.x.x.x"
> options("blpHost" = testDesktop)
> options("blpAutoConnect" = TRUE)
> library(Rblpapi)
Rblpapi version 0.3.8.1 using Blpapi headers 3.8.18.1 and run-time 3.8.18.1.
Please respect the Bloomberg licensing agreement and terms of service.
> blpConnect()
> bdp("IBM US Equity", "NAME")
                                     NAME
IBM US Equity INTL BUSINESS MACHINES CORP
>
```

**Comment by randomee** [comment]
Ergh.  I was changing some git username settings, and borked something.  I'll close this, and make a new pull request.  Sorry about that.

**Comment by eddelbuettel** [comment]
It may be advisable to start with an issue discussing _what_ you want to change along with _how_ and _why_.  Dropping ten-file PRs into our lap is essentially yelling "jump" and we won't answer "how high".

We're busy too.

**Pull request closed without merging**
