### PR TITLE
getBars options vector

### PR DESCRIPTION
**Pull request by joel23888**
@eddelbuettel as you mentioned my commit was "dirty". Sorry about that. I can resubmit clean on Monday or you can take this one and clean it up. Whatever works for you.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
You're not making a ton of sense as this one is still 'dirty' -- including dll files we _clearly_ do not want. (Hint: friends don't let friends use `git commit -a`, stage files manually or from a GUI).

I'll merge and clean up after you.

**Comment by eddelbuettel** [comment]
Do you have a legal name you would care to share so that I can give you proper credit in the [ChangeLog file](https://github.com/Rblp/Rblpapi/blob/master/ChangeLog) ?

**Comment by joel23888** [comment]
Thanks very much and sorry about that. Next time I will ensure it is clean (I had offered to do this on Monday - I am on mobile only this weekend). As I mentioned in the old pull request I think this needs defaults for some options. Any advice on the preferred way to support this would be welcome!

**Comment by joel23888** [comment]
Is it fine just to use my user ID for now?

**Comment by eddelbuettel** [comment]
Then I would not have asked you. I have the id.

**Pull request merged**
